### ISSUE TITLE
Two errors in datasets.py

### ISSUE THREAD

**Issue by realwill** [yuanming-hu/fc4#28]
1. black point of canon1D is 0, not 1, as showed in http://www.cs.sfu.ca/~colour/data/shi_gehler/
2. In NUS-8, It should be img = (raw - darkness_level) / (saturation_level - darkness_level), to normalization the img, but in datasets.py it is saturation_level without darkness_level.

**Comment by realwill** [comment]
anymore, in the datasets.py, I don't think img = (np.clip(raw / raw.max(), 0, 1) * 65535.0).astype(np.uint16) is right, becase raw.max() is the max value in one img, but it should be the max value of all images, and it should be subtract black point for normalization as descripted in NUS-8.

**Comment by yuanming-hu** [comment]
Thanks for the comments.
1. You are right. The difference is negligible, however, since the intensity values are around the magnitude of 2^14.
2. You can consider it a "max-to-white" preprocessing for exposure adjustments. Assuming linear activation, such treatment normalizes the exposure level of all images, adaptively according to the brightness level. The original brightness level is determined by the camera's ISO, aperture and shutter speed and is, in fact, different from camera to camera.
